export const appActions = {
  CHAT_LOGIN: 'CHAT_LOGIN',
  SET_SOCKET_CLIENT: 'SET_SOCKET_CLIENT',
  TOOGLE_ROOM_INFO: 'TOOGLE_ROOM_INFO',
  TOOGLE_ROOM_FORM: 'TOOGLE_ROOM_FORM',
  SET_LOCATION: 'SET_LOCATION',
  SET_ROOM: 'SET_ROOM'
};

export const chatActions = {
  ADD_MESSAGE: 'ADD_MESSAGE',
  RECEIVE_CHAT_MESSAGES: 'RECEIVE_CHAT_MESSAGES'
};

export const roomActions = {
  ADD_ROOM: 'ADD_ROOM',
  LOAD_ROOMS_BY_LOCATION: 'LOAD_ROOMS_BY_LOCATION'
};
