export const appActions = {
  LOGIN: 'LOGIN',
  SET_SOCKET_CLIENT: 'SET_SOCKET_CLIENT',
  TOOGLE_ROOM_INFO: 'TOOGLE_ROOM_INFO',
  SET_ROOM_FORM_VISIBILITY: 'SET_ROOM_FORM_VISIBILITY',
  SET_LOCATION: 'SET_LOCATION',
  SET_ROOM: 'SET_ROOM'
};

export const roomActions = {
  ADD_ROOM: 'ADD_ROOM',
  LOAD_ROOMS_BY_LOCATION: 'LOAD_ROOMS_BY_LOCATION',
  ADD_MESSAGE_CONFIRMATION: 'ADD_MESSAGE_CONFIRMATION'
};
