export const appActions = {
  CHAT_LOGIN: 'CHAT_LOGIN',
  TOOGLE_ROOM_INFO: 'TOOGLE_ROOM_INFO',
  ADD_SOCKET_CLIENT: 'ADD_SOCKET_CLIENT',
  SET_LOCATION: 'SET_LOCATION',
  SET_ROOM: 'SET_ROOM',
  TOOGLE_ROOM_FORM: 'TOOGLE_ROOM_FORM'
};

export const chatActions = {
  ADD_MESSAGE: 'ADD_MESSAGE'
};

export const roomActions = {
  ADD_ROOM: 'ADD_ROOM',
  LOAD_ROOMS_BY_LOCATION: 'LOAD_ROOMS_BY_LOCATION'
};
